.TH "SHORKMINES" 1
.SH NAME
shorkmines \- An ncurses-based minesweeper game played using a keyboard instead of a mouse.
.SH SYNOPSIS
.B shorkmines
[\fB\-w\fR \fIWIDTH\fR]
[\fB\-h\fR \fIHEIGHT\fR]
[\fB\-m\fR \fIDENSITY\fR]
.SH OPTIONS
.TP 4
.BR \-h ", " \-\-height =\fIHEIGHT\fR
Specifies the game board's height (will be clamped if taller than window).
.TP 4
.BR \-\-help\fR
Shows this manual page instead of launching.
.TP 4
.BR \-m ", " \-\-mine-density =\fIDENSITY\fR
Specifies how many mines will be placed on the game board (from 0.0 for no mines to 1.0 for all mines). 0.1 is the default value, roughly translating to about 10% of tiles containing a mine. The game will start to become unplayable at around 0.5.
.TP 4
.BR \-v ", " \-\-version\fR
Displays version number and exits.
.TP 4
.BR \-w ", " \-\-width =\fIWIDTH\fR
Specifies the game board's width (will be clamped if wider than window).
.SH CONTROLS
.TP 4
.BR hjkl " OR " wasd " OR " arrows-keys\fR
Moves the cursor to select a tile
.TP 4
.BR f " OR " g\fR
Places or removes a flag at the selected tile
.TP 4
.BR Space " OR " ,\fR
Opens the selected tile
